### User Sign up endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
"name": "Vlad Bl",
"company": "Company name",
"address": "ul. Test",
"phone": "08828285",
"email": "vladb2368@gmail.com",
"password": "123456789"
}

### User Sign in endpoint

POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
"email": "vladb2368@gmail.com",
"password": "password6"
}

### User sign up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
    "name": "Prem Acharya",
    "company": "Company name",
    "address": "Some address Sydney",
    "phone": "041000000",
    "email": "e2@e.com1",
    "password": "secret222"
}

### User sing in endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json 

{
    "email": "e2@e.com1",
     "password": "secret222"   
}


### User endpoint
GET http://localhost:3001/v1/user/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZsYWRiMjM2OEBnbWFpbC5jb20iLCJpYXQiOjE2NjU0MzQxNDUsImV4cCI6MTY2NTUyMDU0NX0.oWC7ktDBs4uXNS8hyEPOk30er2wazIBvy4Uke2q5ZUM


### Get a user profile endpoint
GET  http://localhost:3001/v1/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZsYWRiMjM2OEBnbWFpbC5jb20iLCJpYXQiOjE2NjgxOTg1MTYsImV4cCI6MTY2ODI4NDkxNn0.VoYuzw95DXx530bhQGzcsB-H6_IPFdjSe-rSpWys6jo

### Get refreshed token

GET http://localhost:3001/v1/tokens
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZsYWRiMjM2OEBnbWFpbC5jb20iLCJpYXQiOjE2Njc5Mjc1MDEsImV4cCI6MTY3MDUxOTUwMX0.ridLEwIBFvemA0usMnFDOusnvvqqU55ZXPGV6HzmL3w


### Password request endpoint
POST http://localhost:3001/v1/user/reset-password
Content-Type: application/json 

{ 
   "email": "vladb2368@gmail.com"
}


### Logout endpoint
DELETE http://localhost:3001/v1/user/reset-password
Content-Type: application/json 

{
   "email": "vladb2368@gmail.com",
   "pin" : "072167",
   "newPassword": "password6"
}


### Password request endpoint
DELETE http://localhost:3001/v1/user/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZsYWRiMjM2OEBnbWFpbC5jb20iLCJpYXQiOjE2Nzg2NTI4NTksImV4cCI6MTY3ODY1NDA1OX0.CalDBr88kY1wniXrUnRWq9wwQosMrtZdJsuZW6mH15k